language: trusty

services:
  - docker

before_install:
#  - docker build -t carlad/sinatra .

script:
  - docker run -it --rm -v $PWD/bin/n:/usr/bin/n ubuntu:18.04 /bin/sh -c "apt update && apt install -y curl && n latest && node -v"
